### ISSUE TITLE
Exempt Route for Route with Path Param

### ISSUE THREAD

**Issue by myang310** [loanzen/falcon-auth#11]
There seems to be no documentation for how to add a route to the `exempt_routes` parameter where the route has a path param, e.g. `/products/{id}`. How do I go about doing that?

**Comment by jcwilson** [comment]
It seems like `falcon-auth` should be using `req.uri_template` rather than `req.path` to match `exempt_routes`. That shouldn't be a difficult change to make.

**Comment by jcwilson** [comment]
Resolved in #18
